### ISSUE TITLE
remove a datapoint pls

### ISSUE THREAD

**Issue by MrZilinXiao** [csmsapp/csmsapp.github.io#116]
Applicants-00000101

没注意到会显示微信头像和昵称，实名上网了属于是...换个微信小号再来贡献dp！

**Comment by Flash-321** [comment]
@MrZilinXiao 搞定啦，看下使用指南https://csmsapp.org/datapoints/ 第三条，可以在这里修改一下头像昵称就匿名了，和微信不是绑定的。https://cloud.seatable.cn/profile/
